FROM python:3.12-slim

WORKDIR /app

COPY Management/requirements.txt .

RUN pip install --no-cache-dir --default-timeout=600 -r requirements.txt

COPY Management/ .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]