# Generated by Django 6.0.7 on 2026-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='keycloak_id',
            field=models.CharField(default='temp-keycloak-id', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
