# Generated by Django 6.0.7 on 2026-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_admin_options_alter_admin_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
