# Generated by Django 6.0.7 on 2026-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
