# Generated by Django 6.0.7 on 2026-08-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin_first_name_admin_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('date_issued', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('accessory_req', models.CharField(max_length=150)),
                ('brand_model', models.CharField(max_length=150)),
                ('serial_Number', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.request')),
            ],
        ),
    ]
