# Generated by Django 6.0.7 on 2026-08-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_request_requestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='request',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='brand_model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='serial_Number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
