# Generated by Django 6.0.7 on 2026-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_request_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
    ]
