# Generated by Django 6.0.7 on 2026-08-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='based_on_stock',
            field=models.BooleanField(default=False),
        ),
    ]
