# Generated by Django 6.0.7 on 2026-08-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_request_based_on_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
