# Generated by Django 6.0.7 on 2026-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_equipment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='overdue_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
